on: [push]

jobs:
  test_build:
    runs-on: ubuntu-latest
    name: Build a project using Arduino CMake Toolchain
    steps:
    - name: Checkout the Arduino CMake Toolchain repository
      uses: actions/checkout@v2
      with:
        repository: a9183756-gh/Arduino-CMake-Toolchain
        path: Arduino-CMake-Toolchain
        ref : release-1.1-dev
    - name: Build the example project of the toolchain
      uses: ./
      with:
        CMAKE_GENERATOR: Unix Makefiles
        ARDUINO_TOOLCHAIN_DIR: $GITHUB_WORKSPACE/Arduino-CMake-Toolchain
        ARDUINO_PROJECT_DIR : $GITHUB_WORKSPACE/Arduino-CMake-Toolchain/Examples
        ARDUINO_BUILD_DIR : $GITHUB_WORKSPACE/build
        ARDUINO_BOARD: esp8266.esp8266.generic
        ARDUINO_BOARD_MANAGER_URL : https://arduino.esp8266.com/stable/package_esp8266com_index.json
